### ISSUE TITLE
ODBC Driver Compatibility

### ISSUE THREAD

**Issue by Downchuck** [Teradata/presto#552]
Does not appear this repo is compatible with the ODBC driver per:
https://community.teradata.com/t5/Presto/FW-connections-issues-of-presto-to-tableau-using-Terdata-ODBC/td-p/72549

**Comment by cawallin** [comment]
Master of this repository doesn't work, but all of the released artifacts will work (for development, we work on branches).

**Comment by cawallin** [comment]
I'm closing this, let us know if you have any other problems!

**Comment by Downchuck** [comment]
@cawallin For following master - should we then look at Sprint branches, if we need a new feature?

This issue seems to stem from the following -- has there been any movement/resolution:

Upstream rejected patch:
https://github.com/prestodb/presto/pull/5868

Based on the issue: Prepared statements and session properties run into HTTP request buffer size limits #5759
https://github.com/prestodb/presto/issues/5759
 
Limited workaround for master branches is to masquerade as an earlier version in the HTTP header response for the Presto HTTP REST:
http://stackoverflow.com/questions/41941676/cannot-connect-tableau-to-presto-on-emr

**Comment by cawallin** [comment]
@Downchuck are you looking to develop against branches? I'm not sure I'd recommend developing against our sprint branches, since those change every two weeks, but the release-*-t branches should be more stable.

There hasn't been any movement thusfar but we're planning to have a discussion about it in the next few days, which will hopefully move things along.

That workaround does seem like it would work. I believe you can also set the server version in the ODBC/JDBC connection string. The long prepared statement patch is backwards compatible on the server side but not on the client side -- aka a TD distribution server can talk to any clients, but the TD distribution client needs to talk to a TD server.
